apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tradiecore-review-documentation
  description: Catalog entities for tradiecore-review-documentation.
spec:
  targets:
    - ./catalog/**/*.yaml
