apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tradiecore-review-documentation-apps
  description: Applications managed within the tradiecore-review-documentation monorepo.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
